### PR TITLE
Use verify-with-signer on --remote

### LINKED ISSUE #108: solana-verify verify-from-repo with --remote fails
While running:`solana-verify verify-from-repo --library-name gamma --program-id GAMMA7meSFWaBXF25oSUgmGRwaW6sCMFLmBNiMSdbHVT https://github.com/GooseFX1/gamma-swap --commit-hash 9a636372886ccad94d4bd524439bba63ca3a942e  --remote`
I get:
```rust
Sending verify command to remote machine...
Encountered an error while attempting to send the job to remote
Error: "{\"status\":\"error\",\"error\":\"The PDA associated with the given signer was not found. Please try again with a valid signer.\"}"
```
I tried various versions. This is only a problem with ` --remote`.
The transaction to add PDA without --remote is here: https://explorer.solana.com/tx/468oQtpTLJqbrHvxfW54UVFkCwbx4tE6yN23ffD2rQAQwWahvEFdS41iL67Df7b5TpaYCPgHN7f7tfvVYNLFrV9c

### PR DESCRIPTION
**Pull request by ngundotra**
Make API behavior consistent between `verify-from-repo --remote` and `remote submit-job`, and improve error messages.

Fixes #108

### CODE REVIEW

File: src/main.rs [hunk 1]
```diff
@@ -1277,18 +1275,16 @@ pub async fn verify_from_repo(
                         return Err(anyhow!("Remote verification only works with mainnet. Please omit the --remote flag to verify locally."));
                     }
 
-                    println!("Sending verify command to remote machine...");
-                    send_job_to_remote(
```
Comment (Woody4618) [inline src/main.rs:1281]: Is send_job_to_remote still used aynwhere now? 🤔

**Review by Woody4618 — APPROVED** [review]
